### ISSUE TITLE
Bloomrpc can't run on Mac M1?

### ISSUE THREAD

**Issue by shizuku-nem** [bloomrpc/bloomrpc#383] opened 2021-09-20 19:22 UTC
I installed bloomRpc by: 

`brew install --cask bloomrpc`

It 's successfully installed~ But can't run.
![image](https://user-images.githubusercontent.com/52918894/134061778-724ba5ca-7b4f-4ea1-ac11-bbf7d692dfdb.png)

I wait for solving issue, thanks!

**Comment by hayleyjames** [comment] 2021-09-21 11:41
Apple blocked the app from opening, but it will run after you grant an exception. You can do that by opening BloomRPC, and then going to **Security & Privacy** in the **System Preferences** app. Click the **Open Anyway** button next to BloomRPC to allow the app to run.

You can find the Apple support page [here](https://support.apple.com/en-gb/guide/mac-help/mh40616/mac).

**Comment by dpangier** [comment] 2021-11-29 23:37
This issue is incorrectly described, and is not really a dupe of #405 

The screen shot and issue described is a lack of code-signing on the binary, which raises an alert with gatekeeper.  This alert is on Intel and Apple Silicon Macs.  Code-signing will solve on both platforms.

BloomRPC works 100% on Apple Silicon (automatically using Rosetta 2).

#405 is a request to build as a universal binary which eliminates the need for MacOS to use Rosetta 2 to run the application.

Suggest both issues are open, and this one is corrected as I describe above.

**Closed** 2023-01-04 07:03 UTC
