### ISSUE TITLE
Import won't work for proto files that include sub proto files

### ISSUE THREAD

**Issue by bentcoder** [bloomrpc/bloomrpc#316] opened 2021-02-18 12:33 UTC
Hi,

As you can see below `service.proto` includes `pagination.proto` so importing `service.proto` causes error below. Any solution to this apart from combining the files?

Thanks

<img width="410" alt="Screen Shot 2021-02-18 at 12 24 48" src="https://user-images.githubusercontent.com/8837278/108356877-974fbe80-71e4-11eb-9867-12bc333c22b1.png">

**service.proto**

```proto
syntax = "proto3";

package feed;

option go_package = "feed;protofeed";

import "feed/pagination.proto";

service FeedService {
    rpc List(ListRequest) returns (ListResponse) {}
}

message ListRequest {
    Filter filter = 1;
}

message ListResponse {
    repeated Feed feeds = 1;
}

message Feed {
    string uuid = 1;
}
```

**pagination.proto**

```proto
syntax = "proto3";

package feed;

option go_package = "feed;protofeed";

message Filter {
    string provider = 1;
    string category = 2;
}
```

**Comment by geret13** [comment] 2021-03-03 12:40
Hey @BentCoder, can you verify for me that you added your proto directory (the directory containing the feed directory containing those two protos) has been added an import path? You can add the folder using the middle button:

![image](https://user-images.githubusercontent.com/2111218/109807362-1520ba80-7c26-11eb-9d66-d5c9d6b29ebd.png)

**Comment by BentCoder** [comment] 2021-03-03 16:15
Hi @geret13 I added the path (see below) but I am still getting the same error when I try to add the actual proto files. Under the `league` folder I have all the proto files but I cannot load them.

![Untitled](https://user-images.githubusercontent.com/8837278/109835744-67b8a180-7c3b-11eb-9b96-5776f6b693a1.png)

**Comment by geret13** [comment] 2021-03-03 16:23
I tested out your case. Sadly I cannot reproduce it.

![image](https://user-images.githubusercontent.com/2111218/109837171-31801f80-7c45-11eb-8337-4725c59d36a9.png)

**Comment by BentCoder** [comment] 2021-03-03 16:45
Interesting! I tried as follow with two options. Both won't work.

1. Click "Import Paths" icon.
  - Click "..." sign to select the folder where all the proto files are stored.
  - Click "+" sign to add it.
  - Click "Close" button.
     - Note: At this point I still don't have any proto files being added to list on the left hand side bar.

2. Click "Import Protos" icon.
  - Select all proto files.
  - Click "Open" button.
    - Note: This is the one that pops up the error.

**Comment by 3choBoomer** [comment] 2021-04-12 14:35
I am also facing the same issue and I have followed all of the steps in this thread.

**Comment by ghstahl** [comment] 2021-04-15 16:18
I have the same issue, but no error is displayed.  Just an empty top-level leaf to my service.  I know my protos are ok because they can be loaded by the grpcui tool.
```
grpcui -import-path C:\dev\myorg\protorepo  -proto C:\dev\myorg\protorepo\myorg\cloud\api\orgs\users\users.proto -proto C:\dev\myorg\protorepo\myorg\cloud\api\orgs\orgs.proto -plaintext localhost:5105
```
My users.proto and orgs.proto are dependent on types in other protos in the ```C:\dev\myorg\protorepo``` path, which grpcui can resolve.

**Comment by vavsab** [comment] 2021-05-23 04:29
> I have the same issue, but no error is displayed. Just an empty top-level leaf to my service. I know my protos are ok because they can be loaded by the grpcui tool.

Please you update to 1.5.3 and check again. Your problem should be fixed now https://github.com/uw-labs/bloomrpc/releases/tag/1.5.3
> 
> ```
> grpcui -import-path C:\dev\myorg\protorepo  -proto C:\dev\myorg\protorepo\myorg\cloud\api\orgs\users\users.proto -proto C:\dev\myorg\protorepo\myorg\cloud\api\orgs\orgs.proto -plaintext localhost:5105
> ```
> 
> My users.proto and orgs.proto are dependent on types in other protos in the `C:\dev\myorg\protorepo` path, which grpcui can resolve.

**Closed** 2023-01-04 07:03 UTC
