### ISSUE TITLE
Error while importing protos with illegal name '}'

### ISSUE THREAD

**Issue by tran302** [bloomrpc/bloomrpc#108] opened 2019-08-10 04:40 UTC
We are using proto message with custom validation rules implemented based on https://github.com/envoyproxy/protoc-gen-validate

Below is sample mssage:
```
syntax = "proto3";
package demo;

service DemoService {
    rpc Demo (DemoRequest) returns (DemoResponse) {}
}
message DemoRequest {
    string number = 1 [(validator.rules).decimal = { }];
}
message DemoResponse {
    string response = 1;
}
```

Above proto fails to import with error ```illegal name '}'``` because there is no specific validation rule defined for ```(validator.rules).decimal```. If I change this to ```[(validator.rules).decimal = { precision: 1 }]```, it imports fine.
Could you please support this format?

**Comment by fenos** [comment] 2019-09-20 15:38
Unfortunately that is a limitation of `protobuf.js` the issue is tracked from here:
protobufjs/protobuf.js#1256

We are thinking to use a forked version of `protobuf.js` until this is merged in

**Comment by gunturaf** [comment] 2021-06-18 07:23
It looks like that protobufjs/protobuf.js#1256 is already merged long time ago, should we update the protobufjs dependency from 6.8.8 to the latest one [6.11.2](https://github.com/protobufjs/protobuf.js/releases/tag/v6.11.2) ? I'm happy to create PR for this

**Closed** 2023-01-04 07:03 UTC
Labels: protobuf.js/unsupported
