### ISSUE TITLE
When will be released version with apple silicon support?

### ISSUE THREAD

**Issue by baza04** [bloomrpc/bloomrpc#405] opened 2021-11-17 18:00 UTC

**Comment by dpangier** [comment] 2021-11-26 23:39
The M1 has been in production Macs for over a year now. I was surprised how few apps are Intel only still.  This, sadly, is one of them.

**Comment by george-angel** [comment] 2021-11-27 08:06
Hello @dpangier we will gladly accept a PR from you.

https://github.com/bloomrpc/bloomrpc/issues/398

**Comment by allan2** [comment] 2021-11-29 19:04
Duplicate of #383

**Closed by allan2** 2021-11-29 19:04 UTC
